using './mcpodatareporting-containerapp.module.bicep'

param appcontainerenv_outputs_azure_container_apps_environment_default_domain = '{{ .Env.APPCONTAINERENV_AZURE_CONTAINER_APPS_ENVIRONMENT_DEFAULT_DOMAIN }}'
param appcontainerenv_outputs_azure_container_apps_environment_id = '{{ .Env.APPCONTAINERENV_AZURE_CONTAINER_APPS_ENVIRONMENT_ID }}'
param appcontainerenv_outputs_azure_container_registry_endpoint = '{{ .Env.APPCONTAINERENV_AZURE_CONTAINER_REGISTRY_ENDPOINT }}'
param appcontainerenv_outputs_azure_container_registry_managed_identity_id = '{{ .Env.APPCONTAINERENV_AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}'
param funcstorage987d1_outputs_blobendpoint = '{{ .Env.FUNCSTORAGE987D1_BLOBENDPOINT }}'
param funcstorage987d1_outputs_queueendpoint = '{{ .Env.FUNCSTORAGE987D1_QUEUEENDPOINT }}'
param funcstorage987d1_outputs_tableendpoint = '{{ .Env.FUNCSTORAGE987D1_TABLEENDPOINT }}'
param mcpodatareporting_containerimage = '{{ .Image }}'
param mcpodatareporting_identity_outputs_clientid = '{{ .Env.MCPODATAREPORTING_IDENTITY_CLIENTID }}'
param mcpodatareporting_identity_outputs_id = '{{ .Env.MCPODATAREPORTING_IDENTITY_ID }}'
