using './blazor-containerapp.module.bicep'

param appcontainerenv_outputs_azure_container_apps_environment_default_domain = '{{ .Env.APPCONTAINERENV_AZURE_CONTAINER_APPS_ENVIRONMENT_DEFAULT_DOMAIN }}'
param appcontainerenv_outputs_azure_container_apps_environment_id = '{{ .Env.APPCONTAINERENV_AZURE_CONTAINER_APPS_ENVIRONMENT_ID }}'
param appcontainerenv_outputs_azure_container_registry_endpoint = '{{ .Env.APPCONTAINERENV_AZURE_CONTAINER_REGISTRY_ENDPOINT }}'
param appcontainerenv_outputs_azure_container_registry_managed_identity_id = '{{ .Env.APPCONTAINERENV_AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}'
param azure_openai_deployment_name_value = '{{ parameter "azure_openai_deployment_name" }}'
param azure_openai_endpoint_value = '{{ parameter "azure_openai_endpoint" }}'
param blazor_containerimage = '{{ .Image }}'
param blazor_containerport = '{{ targetPortOrDefault 8080 }}'
